### ISSUE TITLE
Docker file did not correctly connect wehen setting environment variables

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-lambda-worker#1]
Have not investigated further yet:

C:\Users\ruecker>docker run -e ZEEBE_CLIENT_CLOUD_CLUSTERID='xxx' -e ZEEBE_CLIENT_CLOUD_CLIENTID='xxx' -e ZEEBE_CLIENT_CLOUD_CLIENTSECRET='xxx' -e AWS_ACCESSKEY='xx' -e AWS_SECRET='xxx' -e AWS_REGION='eu-central-1' -p 8080:8080 camunda/zeebe-lambda-worker:SNAPSHOT

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
08:11:43.338 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'zeebeClientLifecycle'; nested exception is java.lang.NullPointerException: target
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at io.zeebe.lambda.ZeebeLambdaWorkerApplication.main(ZeebeLambdaWorkerApplication.java:39)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NullPointerException: target
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(AbstractManagedChannelImplBuilder.java:185)
        at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:136)
        at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:131)
        at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:117)
        at io.zeebe.client.impl.ZeebeClientImpl.buildChannel(ZeebeClientImpl.java:122)
        at io.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:78)
        at io.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:257)
        at io.zeebe.spring.client.config.ZeebeClientSpringConfiguration.lambda$zeebeClientObjectFactory$0(ZeebeClientSpringConfiguration.java:39)
        at io.zeebe.spring.util.ZeebeAutoStartUpLifecycle.start(ZeebeAutoStartUpLifecycle.java:52)
        at io.zeebe.spring.client.ZeebeClientLifecycle.start(ZeebeClientLifecycle.java:47)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
        ... 22 common frames omitted
```

**Comment by berndruecker** [comment]
Works if you use Docker correctly - my bad :-(
